// Code generated by "stringer -type=Key"; DO NOT EDIT.

package eip4361

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Domain-1]
	_ = x[Address-2]
	_ = x[Statement-3]
	_ = x[URI-4]
	_ = x[Version-5]
	_ = x[ChainID-6]
	_ = x[Nonce-7]
	_ = x[IssuedAt-8]
	_ = x[ExpirationTime-9]
	_ = x[NotBefore-10]
	_ = x[RequestID-11]
	_ = x[Resources-12]
}

const _Key_name = "DomainAddressStatementURIVersionChainIDNonceIssuedAtExpirationTimeNotBeforeRequestIDResources"

var _Key_index = [...]uint8{0, 6, 13, 22, 25, 32, 39, 44, 52, 66, 75, 84, 93}

func (i Key) String() string {
	i -= 1
	if i < 0 || i >= Key(len(_Key_index)-1) {
		return "Key(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Key_name[_Key_index[i]:_Key_index[i+1]]
}
